# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 06:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='active',
            field=models.BooleanField(verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Годен с'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Годен до'),
        ),
    ]
