# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0002_auto_20171212_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Промокод'),
        ),
    ]
