"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from myshop.local_envs import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['localhost', '81c2e493.ngrok.io']

ADMINS = ADM

SUIT_CONFIG = {
    'ADMIN_NAME': 'Админка Магазин МедОдежды',
    'MENU_ICONS': {
        'shop': 'icon-folder-open',
        'auth': 'icon-lock',
        'sites': 'icon-ok-circle',
        'cupons': 'icon-qrcode',
        'orders': 'icon-shopping-cart',
        'django_comments': 'icon-thumbs-up',
    }
}


#ALLOWED_HOSTS = ['localhost',]

SITE_ID = 1

СОММЕNТ_МАХ_LENGTH = 1024

СОММЕNТS_HIDE_REМOVED = True


THUМВNAIL_DEFAULT_OPTIONS = {"crop": "smart", "detail": True}

CART_SESSION_ID = 'cart'

# Application definition

INTERNAL_IPS = ['127.0.0.1',]

INSTALLED_APPS = [
    'suit',
    'django.contrib.sites',
    'django_comments',
    # 'django_comments_xtd',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    'cart',
    'orders',
    'cupons',
    'easy_thumbnails',
    #'pure_pagination',
    'debug_toolbar',

]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'myshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = '/static/'


#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join('media')

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


EMAIL_HOST = SMTP
EMAIL_HOST_PASSWORD = PASS
EMAIL_HOST_USER = SITE_MAIL
EMAIL_PORT = '587'
EMAIL_USE_TLS = True
SERVER_EMAIL = SITE_MAIL
DEFAULT_FROM_EMAIL = SITE_MAIL
EMAIL_SUBJECT_PREFIX = "docsimvol.ru: "
STUFF_EMAIL = STUFF
