# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171211_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='sz',
            field=models.CharField(choices=[('S', 'Маленький'), ('M', 'Средний'), ('L', 'Большой'), ('N', 'Не Имеет')], db_index=True, max_length=1, unique=True, verbose_name='Размер'),
        ),
    ]
