# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20171213_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='sz',
            field=models.CharField(choices=[('XS', 'очень Маленький'), ('S', 'Маленький'), ('M', 'Средний'), ('L', 'Большой'), ('XL', 'очень Большой'), ('N', 'Не Имеет')], db_index=True, max_length=2, unique=True, verbose_name='Размер'),
        ),
    ]
