# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20171219_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='shop.Color', verbose_name='Цвет'),
        ),
    ]
