# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='рейтинг')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='shop.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name_plural': 'Рейтинги',
                'ordering': ['rating'],
                'verbose_name': 'Рейтинг',
            },
        ),
    ]
