# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rating_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
                'verbose_name': 'Производитель',
            },
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created'], 'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
    ]
