# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20171220_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firms', to='shop.Firm', verbose_name='Производитель'),
        ),
    ]
