# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='author',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='rating',
            name='email',
            field=models.EmailField(max_length=80, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='rating',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Отобразить на сайте'),
        ),
        migrations.AddField(
            model_name='rating',
            name='ratingcomment',
            field=models.TextField(null=True, verbose_name='Отзыв'),
        ),
    ]
