# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='order',
            name='tlf',
            field=models.CharField(default='7999888777', max_length=20, verbose_name='Телефон'),
        ),
    ]
