# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20171211_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tlf',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
