# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20171211_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Предмет заказа', 'verbose_name_plural': 'Предметы заказа'},
        ),
    ]
